name: aimedbench
channels: [conda-forge, bioconda, defaults]
dependencies:
  - python>=3.10
  - pandas>=2.2
  - numpy>=1.26
  - scikit-learn>=1.4
  - matplotlib>=3.8
  - pyyaml>=6.0
  - snakemake>=8.0
  - pip
  - pip:
      - .
